services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"    # AMQP (для Celery)
      - "15672:15672"  # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5


  bot:
    build:

      context: .

      dockerfile: Dockerfile

    depends_on:
      - rabbitmq

    environment:
        CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
        PYTHONPATH: /docker/telegramqrbot/src

    working_dir: /docker/telegramqrbot

    # Если используешь .env — подключаем
    env_file:
      - .env

    # Монтируем только то, что нужно менять в разработке
    volumes:
      - ./src:/docker/telegramqrbot/src
      - ./data:/docker/telegramqrbot/data

    # Перезапускаем, если упал
    restart: unless-stopped

    # Можно переопределить CMD, но он у тебя и так есть в Dockerfile
    command: python3 src/main.py


  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PYTHONPATH: /docker/telegramqrbot/src
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./src:/docker/telegramqrbot/src
      - ./data:/docker/telegramqrbot/data
    working_dir: /docker/telegramqrbot
    command: celery -A telegramQRbot.celery_app:celery_app worker -l info
    restart: unless-stopped


volumes:
  rabbitmq_data:

